@startuml
activate Trippie

loop not isExit
    Trippie -> UI: in
    activate UI

    UI --> Trippie: fullCommand
    deactivate UI


    Trippie -> Parser: parse
    activate Parser

    create Command
    Parser -> Command: new
    activate Command
    Command -> Parser: command
    deactivate Command

    Parser -> Trippie: command
    deactivate Parser

    opt c is not null

        Trippie -> Command: execute
        activate Command

        Command -> TrippieData:setTripList
        activate TrippieData
        TrippieData --> Command
        deactivate TrippieData

        Command -> UI: print/getline
        activate UI
        UI --> Command
        deactivate UI

        Command --> Trippie
        deactivate Command

    end

    Trippie -> Storage:saveMasterFile/saveTrip
    activate Storage

    Storage --> Trippie
    deactivate Storage


    deactivate Trippie
end

@enduml